from django.contrib import admin
from . import models

# Register your models here.
admin.site.register(models.UserRole)
admin.site.register(models.User)
admin.site.register(models.UserLogs)

admin.site.register(models.Country)
admin.site.register(models.Level)
admin.site.register(models.DeployServer)
admin.site.register(models.Type)
admin.site.register(models.ApprovalReference)
admin.site.register(models.Subject)
admin.site.register(models.SubjectKeyWords)
admin.site.register(models.Document)
admin.site.register(models.Measure)
admin.site.register(models.Slogan)
admin.site.register(models.SloganAnalysis)
admin.site.register(models.DocumentSubject)
admin.site.register(models.DocumentTFIDF)
admin.site.register(models.DocumentSubjectKeywords)
admin.site.register(models.DocumentParagraphs)
admin.site.register(models.DocumentGeneralDefinition)
admin.site.register(models.DocumentNgram)
admin.site.register(models.DocumentDefinition)
admin.site.register(models.ExtractedKeywords)
admin.site.register(models.ReferencesParagraphs)
admin.site.register(models.Graph)
admin.site.register(models.CUBE_DocumentJsonList)
admin.site.register(models.CUBE_Subject_TableData)